### ISSUE TITLE
extract LoRA model error: RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel

### ISSUE THREAD

**Issue by BahzBeih** [lifeisboringsoprogramming/youtube#1]
Peace, thanks alot for all your great work 👍👍👍 , i got this error message when i tried to extract LoRA model using your google colab, the model is trained with Egyptian architect Hassan Fathy architectural style.
here is the model link:
https://huggingface.co/mshakour/hassan-fathy-diffusion-v2

here is my input:

!python sd-scripts/networks/extract_lora_from_models.py \
--save_precision fp16 \
--model_org /content/yhtafnassah.ckpt \
--model_tuned /content/v1-5-pruned-emaonly.safetensors \
--save_to /content/yhtafnassah_Lora_reverse-dim128.safetensors \
--dim 128 

and i got this error message:

2023-06-18 15:47:10.901072: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-18 15:47:11.190622: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-06-18 15:47:12.328491: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-06-18 15:47:12.328626: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-06-18 15:47:12.328654: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
loading SD model : /content/yhtafnassah.ckpt
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/sd-scripts/networks/extract_lora_from_models.py:189 in <module>     │
│                                                                              │
│   186   parser = setup_parser()                                              │
│   187                                                                        │
│   188   args = parser.parse_args()                                           │
│ ❱ 189   svd(args)                                                            │
│   190                                                                        │
│                                                                              │
│ /content/sd-scripts/networks/extract_lora_from_models.py:43 in svd           │
│                                                                              │
│    40   save_dtype = str_to_dtype(args.save_precision)                       │
│    41                                                                        │
│    42   print(f"loading SD model : {args.model_org}")                        │
│ ❱  43   text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffu │
│    44   print(f"loading SD model : {args.model_tuned}")                      │
│    45   text_encoder_t, _, unet_t = model_util.load_models_from_stable_diffu │
│    46                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/library/model_util.py:863 in         │
│ load_models_from_stable_diffusion_checkpoint                                 │
│                                                                              │
│    860 │   converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state │
│    861 │                                                                     │
│    862 │   unet = UNet2DConditionModel(**unet_config).to(device)             │
│ ❱  863 │   info = unet.load_state_dict(converted_unet_checkpoint)            │
│    864 │   print("loading u-net:", info)                                     │
│    865 │                                                                     │
│    866 │   # Convert the VAE model.                                          │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1604 in   │
│ load_state_dict                                                              │
│                                                                              │
│   1601 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_k │
│   1602 │   │                                                                 │
│   1603 │   │   if len(error_msgs) > 0:                                       │
│ ❱ 1604 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {} │
│   1605 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(e │
│   1606 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)       │
│   1607                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for down_blocks.0.attentions.0.proj_in.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for 
down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a 
param with shape torch.Size([320, 1024]) from checkpoint, the shape in current 
model is torch.Size([320, 768]).
        size mismatch for 
down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a 
param with shape torch.Size([320, 1024]) from checkpoint, the shape in current 
model is torch.Size([320, 768]).
        size mismatch for down_blocks.0.attentions.0.proj_out.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for down_blocks.0.attentions.1.proj_in.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for 
down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_k.weight: copying a 
param with shape torch.Size([320, 1024]) from checkpoint, the shape in current 
model is torch.Size([320, 768]).
        size mismatch for 
down_blocks.0.attentions.1.transformer_blocks.0.attn2.to_v.weight: copying a 
param with shape torch.Size([320, 1024]) from checkpoint, the shape in current 
model is torch.Size([320, 768]).
        size mismatch for down_blocks.0.attentions.1.proj_out.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for down_blocks.1.attentions.0.proj_in.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for 
down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a 
param with shape torch.Size([640, 1024]) from checkpoint, the shape in current 
model is torch.Size([640, 768]).
        size mismatch for 
down_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a 
param with shape torch.Size([640, 1024]) from checkpoint, the shape in current 
model is torch.Size([640, 768]).
        size mismatch for down_blocks.1.attentions.0.proj_out.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for down_blocks.1.attentions.1.proj_in.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for 
down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.weight: copying a 
param with shape torch.Size([640, 1024]) from checkpoint, the shape in current 
model is torch.Size([640, 768]).
        size mismatch for 
down_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.weight: copying a 
param with shape torch.Size([640, 1024]) from checkpoint, the shape in current 
model is torch.Size([640, 768]).
        size mismatch for down_blocks.1.attentions.1.proj_out.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for down_blocks.2.attentions.0.proj_in.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for 
down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a 
param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current 
model is torch.Size([1280, 768]).
        size mismatch for 
down_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a 
param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current 
model is torch.Size([1280, 768]).
        size mismatch for down_blocks.2.attentions.0.proj_out.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for down_blocks.2.attentions.1.proj_in.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for 
down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k.weight: copying a 
param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current 
model is torch.Size([1280, 768]).
        size mismatch for 
down_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v.weight: copying a 
param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current 
model is torch.Size([1280, 768]).
        size mismatch for down_blocks.2.attentions.1.proj_out.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for up_blocks.1.attentions.0.proj_in.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for 
up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for 
up_blocks.1.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for up_blocks.1.attentions.0.proj_out.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for up_blocks.1.attentions.1.proj_in.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for 
up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for 
up_blocks.1.attentions.1.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for up_blocks.1.attentions.1.proj_out.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for up_blocks.1.attentions.2.proj_in.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for 
up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for 
up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for up_blocks.1.attentions.2.proj_out.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).
        size mismatch for up_blocks.2.attentions.0.proj_in.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for 
up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([640, 1024]) from checkpoint, the shape in current model 
is torch.Size([640, 768]).
        size mismatch for 
up_blocks.2.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([640, 1024]) from checkpoint, the shape in current model 
is torch.Size([640, 768]).
        size mismatch for up_blocks.2.attentions.0.proj_out.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for up_blocks.2.attentions.1.proj_in.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for 
up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([640, 1024]) from checkpoint, the shape in current model 
is torch.Size([640, 768]).
        size mismatch for 
up_blocks.2.attentions.1.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([640, 1024]) from checkpoint, the shape in current model 
is torch.Size([640, 768]).
        size mismatch for up_blocks.2.attentions.1.proj_out.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for up_blocks.2.attentions.2.proj_in.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for 
up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([640, 1024]) from checkpoint, the shape in current model 
is torch.Size([640, 768]).
        size mismatch for 
up_blocks.2.attentions.2.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([640, 1024]) from checkpoint, the shape in current model 
is torch.Size([640, 768]).
        size mismatch for up_blocks.2.attentions.2.proj_out.weight: copying a 
param with shape torch.Size([640, 640]) from checkpoint, the shape in current 
model is torch.Size([640, 640, 1, 1]).
        size mismatch for up_blocks.3.attentions.0.proj_in.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for 
up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([320, 1024]) from checkpoint, the shape in current model 
is torch.Size([320, 768]).
        size mismatch for 
up_blocks.3.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([320, 1024]) from checkpoint, the shape in current model 
is torch.Size([320, 768]).
        size mismatch for up_blocks.3.attentions.0.proj_out.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for up_blocks.3.attentions.1.proj_in.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for 
up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([320, 1024]) from checkpoint, the shape in current model 
is torch.Size([320, 768]).
        size mismatch for 
up_blocks.3.attentions.1.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([320, 1024]) from checkpoint, the shape in current model 
is torch.Size([320, 768]).
        size mismatch for up_blocks.3.attentions.1.proj_out.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for up_blocks.3.attentions.2.proj_in.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for 
up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_k.weight: copying a param
with shape torch.Size([320, 1024]) from checkpoint, the shape in current model 
is torch.Size([320, 768]).
        size mismatch for 
up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_v.weight: copying a param
with shape torch.Size([320, 1024]) from checkpoint, the shape in current model 
is torch.Size([320, 768]).
        size mismatch for up_blocks.3.attentions.2.proj_out.weight: copying a 
param with shape torch.Size([320, 320]) from checkpoint, the shape in current 
model is torch.Size([320, 320, 1, 1]).
        size mismatch for mid_block.attentions.0.proj_in.weight: copying a param
with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model 
is torch.Size([1280, 1280, 1, 1]).
        size mismatch for 
mid_block.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a param 
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for 
mid_block.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a param 
with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model 
is torch.Size([1280, 768]).
        size mismatch for mid_block.attentions.0.proj_out.weight: copying a 
param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current 
model is torch.Size([1280, 1280, 1, 1]).

**Comment by lifeisboringsoprogramming** [comment]
I think the checkpoint is from sd version 2
I can extract the LoRA using the version 2 flag and the version 2 base checkpoint

```
python networks/extract_lora_from_models.py \
--v2 \
--save_precision fp16 \
--model_org /content/yhtafnassah.ckpt \
--model_tuned /content/512-base-ema.safetensors \
--save_to /content/yhtafnassah_reverse.safetensors \
--dim 128 
```

I downloaded the sd version 2 base checkpoint from
https://huggingface.co/stabilityai/stable-diffusion-2-base/tree/main

**Comment by BahzBeih** [comment]
> I think the checkpoint is from sd version 2 I can extract the LoRA using the version 2 flag and the version 2 base checkpoint
> 
> ```
> python networks/extract_lora_from_models.py \
> --v2 \
> --save_precision fp16 \
> --model_org /content/yhtafnassah.ckpt \
> --model_tuned /content/512-base-ema.safetensors \
> --save_to /content/yhtafnassah_reverse.safetensors \
> --dim 128 
> ```
> 
> I downloaded the sd version 2 base checkpoint from https://huggingface.co/stabilityai/stable-diffusion-2-base/tree/main

thanks a lot for your concern, that explain why the checkpoint merge was fail with other v 1.5 models i have, do you know how to convert the stable diffusion v2 extracted lora to stable diffusion v 1.5 lora?

**Comment by lifeisboringsoprogramming** [comment]
I'm sorry I cannot find anything from sd-scripts that can convert the model from version 2 to version 1. Maybe someone may make one in the future.
